apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
    - name: proxy
      image: proxy:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: TARGET
          value: "https://192.168.49.2:8443"
        - name: CERT_FILE_PATH
          value: "/app/cert/client.crt"
        - name: KEY_FILE_PATH
          value: "/app/cert/client.key"