apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: proxy:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "https://192.168.49.2:8443"
            - name: CERT_FILE_PATH
              value: "/app/cert/client.crt"
            - name: KEY_FILE_PATH
              value: "/app/cert/client.key"

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
spec:
  selector:
    app: proxy
  ports:
    - port: 8080
      targetPort: 8080